### ISSUE TITLE
Add usage docs

### ISSUE THREAD

**Issue by CodyCBakerPhD** [con/nwb2bids#2]
With examples that are easy for a user to run without much work on their end (such as autogenerating empty files) to demonstrate 'at a glance' what the expected workflow, input, and output of this package involves

**Comment by CodyCBakerPhD** [comment]
@TheChymera Any progress on this?

**Comment by TheChymera** [comment]
@CodyCBakerPhD I don't think it's close to mature enough yet, still trying to get the conversion to work with my neuroconv script, this code might change once I use it more after that bit is done.
